household_power_consumption <- read.table(file = "household_power_consumption.txt",header = T,sep = ';',na.strings = '?')
household_power_consumption$dt <- paste(household_power_consumption$Date,household_power_consumption$Time)
household_power_consumption$dt <- strptime(household_power_consumption$dt,format = "%d/%m/%Y %T")
household_power_consumption[household_power_consumption$dt >= strptime("2007-02-01",format = "%Y-%m-%d") & household_power_consumption$dt < strptime('2007-02-03',format = '%Y-%m-%d'),]->selected
png(file="plot3.png")
plot(selected$dt,selected$Sub_metering_1,type = 'l',xlab = '',ylab = 'Energy sub metering')
lines(selected$dt,selected$Sub_metering_2,col='red')
lines(selected$dt,selected$Sub_metering_3,col='blue')
legend('topright',legend = c('Sub_metering_1','Sub_metering_2','Sub_metering_3'),lty = 1,col = c('black','red','blue'))
dev.off()
